# Configurations
title: Metatonic Apps
longtitle: Metatonic Apps
author: metatonic
email: metatonic.app@gmail.com
description: >
  Metatonic Apps.

version: 1.0
gitbook_version: 3.2.3

url: "https://act2lsy.github.io"
baseurl: "/metatonic"
# url: "https://sighingnow.github.io"
# baseurl: "/jekyll-gitbook"
rss: RSS

# bootstrap: use the remote theme for the site itself
#remote_theme: act2lsy/jekyll-gitbook
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  ordered: true
  h_min: 2
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path: /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination: ./_site
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
